version: '3'
services:
  db:
    image: postgres:11
    restart: on-failure:3
    container_name: auth_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  worker:
    stdin_open: true
    container_name: auth_worker
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3030:3000
